version: '3'

services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      JWT_SECRET: secret
      MONGODB_URI: mongodb://mongo:27017/toutdoux
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--logpath", "/dev/null"]

volumes:
  mongo-data:
